// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by: node scripts/generate-capacity-data.js
export type CapacityDatasetProfile = {
  sourceFiles: string[];
  labels: string[];
  distribution: number[];
};

export const CAPACITY_DATASETS: Record<'CREC' | 'RWC', CapacityDatasetProfile> = {
  "CREC": {
    "sourceFiles": [
      "data/capacity/CREC/Copy of CREC Fall 2023.csv",
      "data/capacity/CREC/Copy of CREC Spring 2024.csv",
      "data/capacity/CREC/Copy of CREC Summer 2024.csv",
      "data/capacity/CREC/Copy of Fall 2024 CREC.csv"
    ],
    "labels": [
      "05:45am - 06:44am",
      "06:45am - 07:44am",
      "07:45am - 08:44am",
      "08:45am - 09:44am",
      "09:45am - 10:44am",
      "10:45am - 11:44am",
      "11:45am - 12:44pm",
      "12:45pm - 01:44pm",
      "01:45pm - 02:44pm",
      "02:45pm - 03:44pm",
      "03:45pm - 04:44pm",
      "04:45pm - 05:44pm",
      "05:45pm - 06:44pm",
      "06:45pm - 07:44pm",
      "07:45pm - 08:44pm",
      "08:45pm - 09:44pm",
      "09:45pm - 10:44pm",
      "10:45pm - 10:59pm"
    ],
    "distribution": [
      35,
      31,
      37,
      51,
      53,
      53,
      54,
      53,
      64,
      73,
      77,
      100,
      92,
      86,
      82,
      60,
      36,
      4
    ]
  },
  "RWC": {
    "sourceFiles": [
      "data/capacity/RWC/RWC Fall 2023.csv",
      "data/capacity/RWC/RWC Spring 2024.csv",
      "data/capacity/RWC/RWC Summer 2024.csv"
    ],
    "labels": [
      "05:45am - 06:44am",
      "06:45am - 07:44am",
      "07:45am - 08:44am",
      "08:45am - 09:44am",
      "09:45am - 10:44am",
      "10:45am - 11:44am",
      "11:45am - 12:44pm",
      "12:45pm - 01:44pm",
      "01:45pm - 02:44pm",
      "02:45pm - 03:44pm",
      "03:45pm - 04:44pm",
      "04:45pm - 05:44pm",
      "05:45pm - 06:44pm",
      "06:45pm - 07:44pm",
      "07:45pm - 08:44pm",
      "08:45pm - 09:44pm",
      "09:45pm - 10:44pm",
      "10:45pm - 10:59pm"
    ],
    "distribution": [
      56,
      43,
      41,
      55,
      63,
      71,
      66,
      60,
      72,
      86,
      98,
      100,
      96,
      76,
      57,
      33,
      7,
      0
    ]
  }
};
